theme: minima

header_pages:
  - index.md

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/Aryan77" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/aryanyadav4" }